### ISSUE TITLE
请问下这是什么问题？

### ISSUE THREAD

**Issue by sostuts** [mohuishou/cet#2]
到最后一步。
[root@VM_140_106_centos cet-master]# node index.js 
module.js:471
    throw err;
    ^

Error: Cannot find module './build/Release/cetdecoder-main'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/cet-master/ling-cet-decoder/index.js:5:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

node v6.9.4 gcc 4.8.5

**Comment by mohuishou** [comment]
应该是c++模块的编译问题

**Comment by sostuts** [comment]
请问下有什么解决办法？

**Comment by mohuishou** [comment]
刚刚测试过

**Comment by mohuishou** [comment]
没有问题

**Comment by mohuishou** [comment]
对了，你可能是没有编译
```bash
cd cet
cd ling-cet-decoder
npm install
```
你执行过这个没有

**Comment by sostuts** [comment]
npm install
cd ling-cet-decoder
npm install
cd ..
node index.js


按照这个来的

**Comment by mohuishou** [comment]
那暂时不清楚了

**Comment by mohuishou** [comment]
![qq 20170217005645](https://cloud.githubusercontent.com/assets/15172509/23031451/fc025ac8-f4ab-11e6-8998-9bde0f8b8316.png)

刚重新clone的，的确没有问题

**Comment by sostuts** [comment]
提示Cannot find module './build/Release/cetdecoder-main'
但
[root@VM_140_106_centos cet-master]# ls -a
.  ..  .gitignore  README.md  cet.js  index.js  ling-cet-decoder  node_modules  package.json

**Comment by sostuts** [comment]
你的是什么环境呢？
版本号那些...

**Comment by sostuts** [comment]
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN lifecycle ling-cet-decoder@1.0.3~install: cannot run in wd %s %s (wd=%s) ling-cet-decoder@1.0.3 node-gyp rebuild /root/node/cet-master/ling-cet-decoder
ling-cet-decoder@1.0.3 /root/node/cet-master/ling-cet-decoder

**Comment by sostuts** [comment]
准考证号获取成功！c�}hU�h�V)�}�� 
������@���gW�N��tc�S���t��:���T��Ѝ�0�i�LӠ�!�����`�&����2�l�?n.�@g#@ç�^���7Y�]����0w�
�����I�YK��                                                                                                                   "���������~,L1Ege�עY�l�?6Yb�
。。。
{
  "status": 200,
  "info": "成绩获取成功！",
  "data": "c\ufffd}h\u001aU\ufffdh\u001e\ufffdV)\ufffd}\ufffd\ufffd\u0015\n\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd@\u0010\ufffd\ufffd\ufffdgW\ufffd\u0011N\ufffd\ufffdtc\ufffdS\ufffd\ufffd\ufffdt\ufffd\ufffd:\ufffd\ufffd\ufffdT\ufffd\ufffdЍ\ufffd0\ufffdi\ufffdLӠ\ufffd\u001a!\ufffd\ufffd\ufffd\ufffd\ufffd`\ufffd&\ufffd\ufffd\ufffd\u0014\ufffd2\ufffdl\ufffd?\u0018n\u0013.\ufffd@g#@ç\ufffd\u0004^\ufffd\ufffd\ufffd7Y\ufffd]\ufffd\ufffd\ufffd\ufffd0\u0001w\ufffd\f\"\u001a\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd~,L1Ege\ufffdעY\ufffdl\ufffd?\u00046Yb\u0005\ufffd\r\ufffd\ufffd\ufffd\ufffd\ufffdI\ufffdYK\ufffd\ufffd\u001f"
}


乱码了是什么情况呢？

**Comment by mohuishou** [comment]
我是UbuntuServer16.04 node 6.9.1 

乱码我也遇到过可能是加密方式的问题还有就是那个99宿舍做了一些限制比如说ip等等，这个后面我没有怎么去测试了

**Comment by sostuts** [comment]
getTicket那个返回的是 403 ，
`  var ip = 119+ "." + 16 + "." + rnd(0, 255) + "." + rnd(0, 255);
  request.post({
    url: 'http://find.cet.99sushe.com/search',
    encoding: null,
    headers: {
      'Referer': 'http://find.cet.99sushe.com',
    },
    body: decoder.getEncryptReqBody(cetType, school, name),
    proxies:ip
  }`
不是发送这个嘛？

**Comment by mohuishou** [comment]
是这个
你可以参考一下这个 https://github.com/wssgcg1213/ling-cet-decoder/pull/4

**Comment by sostuts** [comment]
我猜也是ip问题，既然你的能完美运行，密钥代码没有问题，我换个vps试下

**Comment by sostuts** [comment]
可以了，ip的问题。麻烦你了，谢谢。

**Comment by mohuishou** [comment]
没事

**Comment by sostuts** [comment]
密钥改之后，需要反编译拿吗

**Comment by mohuishou** [comment]
应该是的，我也没有去反编译过，这个都是ling-cet-decoder 这个库的大神做的

**Comment by sostuts** [comment]
好像他的cetdecoder-main.cc 文件里面的密钥跟你的不一样？ 你更新过了么？

**Comment by mohuishou** [comment]
嗯嗯，我的更新过

**Comment by mohuishou** [comment]
去年6月成绩出来之后，密钥就换过一次， 不知道这次会不会换

**Comment by sostuts** [comment]
你反编译拿到的密钥么

**Comment by mohuishou** [comment]
不是，是别人反编译拿到的

**Comment by sostuts** [comment]
今天折腾了半天ida，没有什么发现233 ， 好想请教下那些大牛
